CREATE TABLE [dbo.pragmatic].[Projections]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[TopRate] DECIMAL(18, 4) NOT NULL,
	[TopEquity] DECIMAL(18, 2) NOT NULL,
	[Steps] DECIMAL(18, 2) NOT NULL,
	[TopLongs] DECIMAL(18, 2) NOT NULL,
	[TopShorts] DECIMAL(18, 2) NOT NULL,
	[BottomRate] DECIMAL(18, 4) NOT NULL,
	[BottomEquity] DECIMAL(18, 2) NOT NULL,
	[BottomBalance] DECIMAL(18, 2) NOT NULL,
	[BottomLongs] DECIMAL(18, 2) NOT NULL,
	[BottomShorts] DECIMAL(18, 2) NOT NULL,
	[UpRate] DECIMAL(18, 4) NOT NULL,
	[UpEquity] DECIMAL(18, 2) NOT NULL,
	[UpBalance] DECIMAL(18, 2) NOT NULL,
	[UpLongs] DECIMAL(18, 2) NOT NULL,
	[UpShorts] DECIMAL(18, 2) NOT NULL,
	[DownRate] DECIMAL(18, 4) NOT NULL,
	[DownEquity] DECIMAL(18, 2) NOT NULL,
	[DownBalance] DECIMAL(18, 2) NOT NULL,
	[DownLongs] DECIMAL(18, 2) NOT NULL,
	[DownShorts] DECIMAL(18, 2) NOT NULL,
	[CenterRate] DECIMAL(18, 4) NOT NULL,
	[CenterEquity] DECIMAL(18, 2) NOT NULL,
	[CenterBalance] DECIMAL(18, 2) NOT NULL,
	[CenterLongs] DECIMAL(18, 2) NOT NULL,
	[CenterShorts] DECIMAL(18, 2) NOT NULL,
	[LastUpdated] DATETIME2 NOT NULL, 
    CONSTRAINT [FK_Projections_Accounts] FOREIGN KEY ([Id]) REFERENCES [dbo.pragmatic].[Accounts]([Id])
)
